name: auth_firebaseuas
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.15.0-116.0.dev <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.1
  equatable: ^2.0.3
  firebase_auth: ^3.2.0
  firebase_core: 1.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  get: 4.5.1
  google_fonts: ^2.1.0
  http: ^0.13.4
  tmdb_api: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/splash.png
